// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF9ZK0F_SD_DPcky0u_-GofOWu6_hTf0g',
    appId: '1:961617590176:web:7e0ee8cfd4e11d73cbd6c5',
    messagingSenderId: '961617590176',
    projectId: 'futterbackend',
    authDomain: 'futterbackend.firebaseapp.com',
    storageBucket: 'futterbackend.firebasestorage.app',
    measurementId: 'G-FE2R095P6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0rUYi6rwQ73v_anIQKCFH_5eTZpzev8',
    appId: '1:961617590176:android:ecbc2722fa151e33cbd6c5',
    messagingSenderId: '961617590176',
    projectId: 'futterbackend',
    storageBucket: 'futterbackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAygN7goPlkF9ohYuqZh1Su5rfIuhMAHl8',
    appId: '1:961617590176:ios:373c9f3c190bd4e2cbd6c5',
    messagingSenderId: '961617590176',
    projectId: 'futterbackend',
    storageBucket: 'futterbackend.firebasestorage.app',
    iosBundleId: 'com.example.eventFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAygN7goPlkF9ohYuqZh1Su5rfIuhMAHl8',
    appId: '1:961617590176:ios:373c9f3c190bd4e2cbd6c5',
    messagingSenderId: '961617590176',
    projectId: 'futterbackend',
    storageBucket: 'futterbackend.firebasestorage.app',
    iosBundleId: 'com.example.eventFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF9ZK0F_SD_DPcky0u_-GofOWu6_hTf0g',
    appId: '1:961617590176:web:db094e19a539f29dcbd6c5',
    messagingSenderId: '961617590176',
    projectId: 'futterbackend',
    authDomain: 'futterbackend.firebaseapp.com',
    storageBucket: 'futterbackend.firebasestorage.app',
    measurementId: 'G-X6NRDZ23YN',
  );
}
